"""
Django settings for the project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
def get_file_name_only(path):
	return os.path.splitext(os.path.basename(path))[0]
CONFIG_FILE_IN_USE = get_file_name_only(__file__)  # Custom setting

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Custom settings
CONF_DIR = os.path.join(os.path.dirname(BASE_DIR), 'conf')
DATA_DIR = os.path.join(os.path.dirname(BASE_DIR), 'data')
PROJECT_NAME = 'uptospeed'
DOMAIN_NAME = 'uptospeed.tech'


# Email
# All outbound email will have this as the From: header, unless overridden
DEFAULT_FROM_EMAIL = '"' + PROJECT_NAME + '" <support@' + DOMAIN_NAME + '>'

# People who should receive website error notifications
ADMINS = [
	('Admin', 'admin@' + DOMAIN_NAME),
]

# Separate list of admins who should receive broken link notifications
MANAGERS = ADMINS

# Emails sent to ADMINS and MANAGERS will come from this address
SERVER_EMAIL = DEFAULT_FROM_EMAIL


# Application definition

INSTALLED_APPS = [
	# Django stuff
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',

	# Our core app
	'system',

	# Extra apps

	# Custom Django extensions
	'django_rotate_secret_key',
	'django_maint_mode_toggle',
	'django_generate_dynamic_configs',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.common.BrokenLinkEmailsMiddleware',  # Notify MANAGERS of 404 errors, when DEBUG=False and the request includes a referer. Must come before any middleware that intercepts 404 errors, such as LocaleMiddleware or FlatpageFallbackMiddleware
]

ROOT_URLCONF = 'system.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'system.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

# Base URL to use for static files when {% static '<file>' %} is used
STATIC_URL = '/static/'
# Location to collect static files to when the collectstatic command is run
STATIC_ROOT = os.path.join(DATA_DIR, "static")

# Base URL to use for media files; access from templates with {{ MEDIA_URL }} if django.template.context_processors.media is configured
MEDIA_URL = '/media/'
# Location to hold user-uploaded files
MEDIA_ROOT = os.path.join(DATA_DIR, "media")
