#!/usr/bin/env sh

# Returns 'development', 'staging', or 'production' after determining which environment this script exists within
# Assume production environment if ../whichenv.txt and ../conf/whichenv.txt do not exist.

cd $(dirname $0)

# Determine which settings file to use

if [ -f ../whichenv.txt ]; then
	read settings_file < ../whichenv.txt
elif [ -f ../conf/whichenv.txt ]; then
	read settings_file < ../conf/whichenv.txt
else
	settings_file="production"
fi
echo -n $settings_file
